/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkapaKontoRouteImport } from './routes/skapa-konto'
import { Route as OmPongiRouteImport } from './routes/om-pongi'
import { Route as LoggaInRouteImport } from './routes/logga-in'
import { Route as KomIgangRouteImport } from './routes/kom-igang'
import { Route as IntegritetRouteImport } from './routes/integritet'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KurserIndexRouteImport } from './routes/kurser.index'
import { Route as KurserCourseSlugRouteImport } from './routes/kurser.$courseSlug'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHemRouteImport } from './routes/_authenticated/hem'
import { Route as AuthenticatedKurserCourseSlugLessonIdRouteImport } from './routes/_authenticated/kurser.$courseSlug.$lessonId'

const SkapaKontoRoute = SkapaKontoRouteImport.update({
  id: '/skapa-konto',
  path: '/skapa-konto',
  getParentRoute: () => rootRouteImport,
} as any)
const OmPongiRoute = OmPongiRouteImport.update({
  id: '/om-pongi',
  path: '/om-pongi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggaInRoute = LoggaInRouteImport.update({
  id: '/logga-in',
  path: '/logga-in',
  getParentRoute: () => rootRouteImport,
} as any)
const KomIgangRoute = KomIgangRouteImport.update({
  id: '/kom-igang',
  path: '/kom-igang',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetRoute = IntegritetRouteImport.update({
  id: '/integritet',
  path: '/integritet',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KurserIndexRoute = KurserIndexRouteImport.update({
  id: '/kurser/',
  path: '/kurser/',
  getParentRoute: () => rootRouteImport,
} as any)
const KurserCourseSlugRoute = KurserCourseSlugRouteImport.update({
  id: '/kurser/$courseSlug',
  path: '/kurser/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHemRoute = AuthenticatedHemRouteImport.update({
  id: '/hem',
  path: '/hem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKurserCourseSlugLessonIdRoute =
  AuthenticatedKurserCourseSlugLessonIdRouteImport.update({
    id: '/kurser/$courseSlug/$lessonId',
    path: '/kurser/$courseSlug/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/integritet': typeof IntegritetRoute
  '/kom-igang': typeof KomIgangRoute
  '/logga-in': typeof LoggaInRoute
  '/om-pongi': typeof OmPongiRoute
  '/skapa-konto': typeof SkapaKontoRoute
  '/hem': typeof AuthenticatedHemRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/kurser/$courseSlug': typeof KurserCourseSlugRoute
  '/kurser/': typeof KurserIndexRoute
  '/kurser/$courseSlug/$lessonId': typeof AuthenticatedKurserCourseSlugLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/integritet': typeof IntegritetRoute
  '/kom-igang': typeof KomIgangRoute
  '/logga-in': typeof LoggaInRoute
  '/om-pongi': typeof OmPongiRoute
  '/skapa-konto': typeof SkapaKontoRoute
  '/hem': typeof AuthenticatedHemRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/kurser/$courseSlug': typeof KurserCourseSlugRoute
  '/kurser': typeof KurserIndexRoute
  '/kurser/$courseSlug/$lessonId': typeof AuthenticatedKurserCourseSlugLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/budget': typeof BudgetRoute
  '/integritet': typeof IntegritetRoute
  '/kom-igang': typeof KomIgangRoute
  '/logga-in': typeof LoggaInRoute
  '/om-pongi': typeof OmPongiRoute
  '/skapa-konto': typeof SkapaKontoRoute
  '/_authenticated/hem': typeof AuthenticatedHemRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/kurser/$courseSlug': typeof KurserCourseSlugRoute
  '/kurser/': typeof KurserIndexRoute
  '/_authenticated/kurser/$courseSlug/$lessonId': typeof AuthenticatedKurserCourseSlugLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/integritet'
    | '/kom-igang'
    | '/logga-in'
    | '/om-pongi'
    | '/skapa-konto'
    | '/hem'
    | '/onboarding'
    | '/profil'
    | '/kurser/$courseSlug'
    | '/kurser/'
    | '/kurser/$courseSlug/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/integritet'
    | '/kom-igang'
    | '/logga-in'
    | '/om-pongi'
    | '/skapa-konto'
    | '/hem'
    | '/onboarding'
    | '/profil'
    | '/kurser/$courseSlug'
    | '/kurser'
    | '/kurser/$courseSlug/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/budget'
    | '/integritet'
    | '/kom-igang'
    | '/logga-in'
    | '/om-pongi'
    | '/skapa-konto'
    | '/_authenticated/hem'
    | '/_authenticated/onboarding'
    | '/_authenticated/profil'
    | '/kurser/$courseSlug'
    | '/kurser/'
    | '/_authenticated/kurser/$courseSlug/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BudgetRoute: typeof BudgetRoute
  IntegritetRoute: typeof IntegritetRoute
  KomIgangRoute: typeof KomIgangRoute
  LoggaInRoute: typeof LoggaInRoute
  OmPongiRoute: typeof OmPongiRoute
  SkapaKontoRoute: typeof SkapaKontoRoute
  KurserCourseSlugRoute: typeof KurserCourseSlugRoute
  KurserIndexRoute: typeof KurserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skapa-konto': {
      id: '/skapa-konto'
      path: '/skapa-konto'
      fullPath: '/skapa-konto'
      preLoaderRoute: typeof SkapaKontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-pongi': {
      id: '/om-pongi'
      path: '/om-pongi'
      fullPath: '/om-pongi'
      preLoaderRoute: typeof OmPongiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logga-in': {
      id: '/logga-in'
      path: '/logga-in'
      fullPath: '/logga-in'
      preLoaderRoute: typeof LoggaInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kom-igang': {
      id: '/kom-igang'
      path: '/kom-igang'
      fullPath: '/kom-igang'
      preLoaderRoute: typeof KomIgangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritet': {
      id: '/integritet'
      path: '/integritet'
      fullPath: '/integritet'
      preLoaderRoute: typeof IntegritetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurser/': {
      id: '/kurser/'
      path: '/kurser'
      fullPath: '/kurser/'
      preLoaderRoute: typeof KurserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurser/$courseSlug': {
      id: '/kurser/$courseSlug'
      path: '/kurser/$courseSlug'
      fullPath: '/kurser/$courseSlug'
      preLoaderRoute: typeof KurserCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hem': {
      id: '/_authenticated/hem'
      path: '/hem'
      fullPath: '/hem'
      preLoaderRoute: typeof AuthenticatedHemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kurser/$courseSlug/$lessonId': {
      id: '/_authenticated/kurser/$courseSlug/$lessonId'
      path: '/kurser/$courseSlug/$lessonId'
      fullPath: '/kurser/$courseSlug/$lessonId'
      preLoaderRoute: typeof AuthenticatedKurserCourseSlugLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHemRoute: typeof AuthenticatedHemRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedKurserCourseSlugLessonIdRoute: typeof AuthenticatedKurserCourseSlugLessonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHemRoute: AuthenticatedHemRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedKurserCourseSlugLessonIdRoute:
    AuthenticatedKurserCourseSlugLessonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BudgetRoute: BudgetRoute,
  IntegritetRoute: IntegritetRoute,
  KomIgangRoute: KomIgangRoute,
  LoggaInRoute: LoggaInRoute,
  OmPongiRoute: OmPongiRoute,
  SkapaKontoRoute: SkapaKontoRoute,
  KurserCourseSlugRoute: KurserCourseSlugRoute,
  KurserIndexRoute: KurserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
