/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkapaKontoRouteImport } from './routes/skapa-konto'
import { Route as OmPongiRouteImport } from './routes/om-pongi'
import { Route as LoggaInRouteImport } from './routes/logga-in'
import { Route as IntegritetRouteImport } from './routes/integritet'
import { Route as GlomtLosenordRouteImport } from './routes/glomt-losenord'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AterstallLosenordRouteImport } from './routes/aterstall-losenord'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KurserIndexRouteImport } from './routes/kurser.index'
import { Route as KurserCourseSlugRouteImport } from './routes/kurser.$courseSlug'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLektionLessonIdRouteImport } from './routes/_authenticated/lektion.$lessonId'

const SkapaKontoRoute = SkapaKontoRouteImport.update({
  id: '/skapa-konto',
  path: '/skapa-konto',
  getParentRoute: () => rootRouteImport,
} as any)
const OmPongiRoute = OmPongiRouteImport.update({
  id: '/om-pongi',
  path: '/om-pongi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggaInRoute = LoggaInRouteImport.update({
  id: '/logga-in',
  path: '/logga-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetRoute = IntegritetRouteImport.update({
  id: '/integritet',
  path: '/integritet',
  getParentRoute: () => rootRouteImport,
} as any)
const GlomtLosenordRoute = GlomtLosenordRouteImport.update({
  id: '/glomt-losenord',
  path: '/glomt-losenord',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AterstallLosenordRoute = AterstallLosenordRouteImport.update({
  id: '/aterstall-losenord',
  path: '/aterstall-losenord',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KurserIndexRoute = KurserIndexRouteImport.update({
  id: '/kurser/',
  path: '/kurser/',
  getParentRoute: () => rootRouteImport,
} as any)
const KurserCourseSlugRoute = KurserCourseSlugRouteImport.update({
  id: '/kurser/$courseSlug',
  path: '/kurser/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLektionLessonIdRoute =
  AuthenticatedLektionLessonIdRouteImport.update({
    id: '/lektion/$lessonId',
    path: '/lektion/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aterstall-losenord': typeof AterstallLosenordRoute
  '/auth': typeof AuthRoute
  '/glomt-losenord': typeof GlomtLosenordRoute
  '/integritet': typeof IntegritetRoute
  '/logga-in': typeof LoggaInRoute
  '/om-pongi': typeof OmPongiRoute
  '/skapa-konto': typeof SkapaKontoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/kurser/$courseSlug': typeof KurserCourseSlugRoute
  '/kurser/': typeof KurserIndexRoute
  '/lektion/$lessonId': typeof AuthenticatedLektionLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aterstall-losenord': typeof AterstallLosenordRoute
  '/auth': typeof AuthRoute
  '/glomt-losenord': typeof GlomtLosenordRoute
  '/integritet': typeof IntegritetRoute
  '/logga-in': typeof LoggaInRoute
  '/om-pongi': typeof OmPongiRoute
  '/skapa-konto': typeof SkapaKontoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/kurser/$courseSlug': typeof KurserCourseSlugRoute
  '/kurser': typeof KurserIndexRoute
  '/lektion/$lessonId': typeof AuthenticatedLektionLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aterstall-losenord': typeof AterstallLosenordRoute
  '/auth': typeof AuthRoute
  '/glomt-losenord': typeof GlomtLosenordRoute
  '/integritet': typeof IntegritetRoute
  '/logga-in': typeof LoggaInRoute
  '/om-pongi': typeof OmPongiRoute
  '/skapa-konto': typeof SkapaKontoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/kurser/$courseSlug': typeof KurserCourseSlugRoute
  '/kurser/': typeof KurserIndexRoute
  '/_authenticated/lektion/$lessonId': typeof AuthenticatedLektionLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aterstall-losenord'
    | '/auth'
    | '/glomt-losenord'
    | '/integritet'
    | '/logga-in'
    | '/om-pongi'
    | '/skapa-konto'
    | '/dashboard'
    | '/onboarding'
    | '/profil'
    | '/kurser/$courseSlug'
    | '/kurser/'
    | '/lektion/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aterstall-losenord'
    | '/auth'
    | '/glomt-losenord'
    | '/integritet'
    | '/logga-in'
    | '/om-pongi'
    | '/skapa-konto'
    | '/dashboard'
    | '/onboarding'
    | '/profil'
    | '/kurser/$courseSlug'
    | '/kurser'
    | '/lektion/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aterstall-losenord'
    | '/auth'
    | '/glomt-losenord'
    | '/integritet'
    | '/logga-in'
    | '/om-pongi'
    | '/skapa-konto'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/profil'
    | '/kurser/$courseSlug'
    | '/kurser/'
    | '/_authenticated/lektion/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AterstallLosenordRoute: typeof AterstallLosenordRoute
  AuthRoute: typeof AuthRoute
  GlomtLosenordRoute: typeof GlomtLosenordRoute
  IntegritetRoute: typeof IntegritetRoute
  LoggaInRoute: typeof LoggaInRoute
  OmPongiRoute: typeof OmPongiRoute
  SkapaKontoRoute: typeof SkapaKontoRoute
  KurserCourseSlugRoute: typeof KurserCourseSlugRoute
  KurserIndexRoute: typeof KurserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skapa-konto': {
      id: '/skapa-konto'
      path: '/skapa-konto'
      fullPath: '/skapa-konto'
      preLoaderRoute: typeof SkapaKontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-pongi': {
      id: '/om-pongi'
      path: '/om-pongi'
      fullPath: '/om-pongi'
      preLoaderRoute: typeof OmPongiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logga-in': {
      id: '/logga-in'
      path: '/logga-in'
      fullPath: '/logga-in'
      preLoaderRoute: typeof LoggaInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritet': {
      id: '/integritet'
      path: '/integritet'
      fullPath: '/integritet'
      preLoaderRoute: typeof IntegritetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glomt-losenord': {
      id: '/glomt-losenord'
      path: '/glomt-losenord'
      fullPath: '/glomt-losenord'
      preLoaderRoute: typeof GlomtLosenordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aterstall-losenord': {
      id: '/aterstall-losenord'
      path: '/aterstall-losenord'
      fullPath: '/aterstall-losenord'
      preLoaderRoute: typeof AterstallLosenordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurser/': {
      id: '/kurser/'
      path: '/kurser'
      fullPath: '/kurser/'
      preLoaderRoute: typeof KurserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurser/$courseSlug': {
      id: '/kurser/$courseSlug'
      path: '/kurser/$courseSlug'
      fullPath: '/kurser/$courseSlug'
      preLoaderRoute: typeof KurserCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lektion/$lessonId': {
      id: '/_authenticated/lektion/$lessonId'
      path: '/lektion/$lessonId'
      fullPath: '/lektion/$lessonId'
      preLoaderRoute: typeof AuthenticatedLektionLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedLektionLessonIdRoute: typeof AuthenticatedLektionLessonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedLektionLessonIdRoute: AuthenticatedLektionLessonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AterstallLosenordRoute: AterstallLosenordRoute,
  AuthRoute: AuthRoute,
  GlomtLosenordRoute: GlomtLosenordRoute,
  IntegritetRoute: IntegritetRoute,
  LoggaInRoute: LoggaInRoute,
  OmPongiRoute: OmPongiRoute,
  SkapaKontoRoute: SkapaKontoRoute,
  KurserCourseSlugRoute: KurserCourseSlugRoute,
  KurserIndexRoute: KurserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
